version: "3"

services:
  # start any containers you want proxied with an env var:
  # docker run -e VIRTUAL_HOST=foo.bar.com  ...
  # note: "The jwilder/nginx-proxy image is built for x86 and doesn't run on armhf / RaspberryPi out of the box. You need to modify the Dockerfile and build the image yourself." - bjoernbusch (https://github.com/nginx-proxy/nginx-proxy/issues/715)
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    networks:
      - proxy
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./vhost.d:/etc/nginx/vhost.d:ro"

  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    restart: always
    networks:
      - proxy
    environment:
      - VIRTUAL_HOST=${PORTAINER_VHOST}
      - VIRTUAL_PORT=9000
    ports:
      - 8000:8000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    depends_on:
      - "nginx-proxy"
      
  # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "853:53/tcp"
      - "853:53/udp"
      - "867:67/udp"
      - "8080:80/tcp"
      - "8443:443/tcp"
    environment:
      TZ: 'Europe/Berlin'
      DNS1: '1.1.1.1' # Cloudflare DNS
      DNS2: '1.0.0.1' # Cloudflare DNS
      WEBPASSWORD: '${PIHOLE_PW}'
      CONDITIONAL_FORWARDING: "true"
      CONDITIONAL_FORWARDING_IP: ${PIHOLE_ROUTER_IP}
      CONDITIONAL_FORWARDING_DOMAIN: ${PIHOLE_NETWORK_DOMAIN}
      ServerIP: ${PIHOLE_HOST_IP}
      ServerIPv6: ${PIHOLE_HOST_IPV6}
      VIRTUAL_HOST: ${PIHOLE_VHOST}
      VIRTUAL_PORT: 80
    dns:
      # set default dns to use (if 127.0.0.1 is not available it uses Cloudfares DNS)
      - 127.0.0.1
      - 1.1.1.1
    # Volumes store your data between container upgrades
    volumes:
      - "/etc/pihole/:/etc/pihole/"
      - "/etc/dnsmasq.d/:/etc/dnsmasq.d/"
      - "/pihole/pihole.log:/var/log/pihole.log"
    # REMINDER: create an empty file to prevent creating a directory - this would not allow to start pihole-FTL
    # (https://github.com/pi-hole/docker-pi-hole/issues/645#issuecomment-670809672)
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    depends_on:
      - "nginx-proxy"
      
  plex:
    image: jaymoulin/plex:latest
    container_name: plex
    restart: always
    volumes:
      - /media/:${PLEX_MEDIA_PATH}
    network_mode: host
    depends_on:
      - "nginx-proxy"

networks:
  proxy:

volumes:
  portainer_data:
